repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.5.7  # 최신 버전 확인: https://github.com/astral-sh/ruff-pre-commit/releases
    hooks:
      - id: ruff
        args: ["--fix", "--exit-non-zero-on-fix"]
      - id: ruff-format
