# Generated by Django 5.2.5 on 2025-10-08 13:46

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Food",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("item_name", models.CharField(max_length=50)),
                ("item_code", models.IntegerField()),
                ("kind_name", models.CharField(max_length=20)),
                ("kind_code", models.IntegerField()),
                ("rank_name", models.CharField(max_length=20)),
                ("rank_code", models.IntegerField()),
                ("unit", models.CharField(max_length=20)),
                ("price", models.PositiveIntegerField()),
                ("collected_date", models.DateField()),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("fruit", "과일"),
                            ("grain", "곡물/견과"),
                            ("seafood", "수산물"),
                            ("meat", "고기"),
                            ("red_pepper", "고추류"),
                            ("cabbage", "배추류"),
                            ("vegetable", "채소류"),
                            ("mushroom", "버섯류"),
                            ("food", "식품"),
                            ("sauce", "양념류"),
                            ("fruit/vegetable", "과채류"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "region",
                    models.CharField(
                        choices=[
                            ("0000", "전체"),
                            ("1101", "서울"),
                            ("2100", "부산"),
                            ("2200", "대구"),
                            ("2300", "인천"),
                            ("2401", "광주"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "price_change_rate",
                    models.CharField(blank=True, max_length=10, null=True),
                ),
            ],
        ),
    ]
