# Generated by Django 5.2.5 on 2025-10-08 14:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("food", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="food",
            name="sales_type",
            field=models.CharField(
                choices=[("01", "소매"), ("02", "도매")], default="01", max_length=10
            ),
            preserve_default=False,
        ),
    ]
