# Generated by Django 4.2.25 on 2025-10-10 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("food", "0002_food_sales_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="food",
            name="category",
            field=models.CharField(
                choices=[
                    ("fruit", "과일"),
                    ("grain", "곡물·견과"),
                    ("seafood", "수산물"),
                    ("meat", "고기·단백질"),
                    ("red_pepper", "고추류"),
                    ("cabbage", "배추류"),
                    ("vegetable", "채소류"),
                    ("mushroom", "버섯류"),
                    ("food", "식품"),
                    ("sauce", "양념류"),
                    ("fruit/vegetable", "과채류"),
                ],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="food",
            name="region",
            field=models.CharField(
                choices=[
                    ("0000", "전체"),
                    ("1101", "서울"),
                    ("2100", "부산"),
                    ("2200", "대구"),
                    ("2300", "인천"),
                    ("2401", "광주"),
                    ("2501", "대전"),
                    ("2601", "울산"),
                    ("3111", "수원"),
                    ("3214", "강릉"),
                    ("3211", "춘천"),
                    ("3311", "청주"),
                    ("3511", "전주"),
                    ("3711", "포항"),
                    ("3911", "제주"),
                    ("3113", "의정부"),
                    ("3613", "순천"),
                    ("3714", "안동"),
                    ("3814", "창원"),
                    ("3145", "용인"),
                    ("2701", "세종"),
                    ("3112", "성남"),
                    ("3138", "고양"),
                    ("3411", "천안"),
                    ("3818", "김해"),
                ],
                max_length=20,
            ),
        ),
    ]
