# Generated by Django 4.2.25 on 2025-10-10 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("food", "0003_alter_food_category_alter_food_region"),
    ]

    operations = [
        migrations.CreateModel(
            name="Store",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=20)),
                ("number", models.CharField(max_length=20)),
                ("business_info", models.CharField(max_length=100)),
                ("image", models.URLField(max_length=150)),
                ("address_link", models.URLField(max_length=150)),
                ("address", models.CharField(max_length=50)),
                ("food_category", models.JSONField(default=list)),
            ],
        ),
    ]
