name: Deploy to EC2 on main

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Add SSH key
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.EC2_SSH_KEY }}

      - name: Trust EC2 host
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan -p ${{ secrets.EC2_PORT }} ${{ secrets.EC2_HOST }} >> ~/.ssh/known_hosts

      - name: Remote deploy
        env:
          PROJECT_DIR: ${{ secrets.PROJECT_DIR }}
          DJANGO_SECRET_KEY: ${{ secrets.DJANGO_SECRET_KEY }}
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
          DJANGO_ALLOWED_HOSTS: ${{ secrets.DJANGO_ALLOWED_HOSTS }}
          REDIS_HOST: ${{ secrets.REDIS_HOST }}
          REDIS_PORT: ${{ secrets.REDIS_PORT }}
        run: |
          ssh -p ${{ secrets.EC2_PORT }} ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} "\
            export DJANGO_SECRET_KEY='${DJANGO_SECRET_KEY}' \
                   DATABASE_URL='${DATABASE_URL}' \
                   DJANGO_ALLOWED_HOSTS='${DJANGO_ALLOWED_HOSTS}' \
                   REDIS_HOST='${REDIS_HOST}' \
                   REDIS_PORT='${REDIS_PORT}'; \
            bash -lc 'bash ${PROJECT_DIR}/deploy.sh' \
          "